services:
  mysql-balance:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: balance
    ports:
      - "3307:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
      